spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data-source:
    url: jdbc:postgresql://localhost:5433/story
    username: postgres
    password: asdqwe123
  flyway:
    baseline-on-migrate: true




