//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 07:09:59 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://griddynamics.com/finalprojectspring/ws/greeting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.griddynamics.finalprojectspring.ws.com.griddynamics.finalprojectspring.ws;
